"""
This dictionary is used for the company renaming strategy.
The idea behind this is to be able to have a same naming convention for several companies
as they might have changed between yearly forbes 2000 ranking posts.

We just look to emphasize on renaming companies that have been named differently between rankings,
but not companies which are part of a conglomerate or that have been bought by bigger companies in other rankings.
"""

REBRAND = {
    'ASE-Advanced Semiconductor': 'ASE Technology Holding',
    'Adani Ports & Special Economic Zone': 'Adani Enterprises',
    'Admiral Group plc': 'Admiral Group',
    'Adobe Systems': 'Adobe',
    'Advanced Micro': 'Advanced Micro Devices',
    'Agile Property Holdings': 'Agile Group Holdings',
    'Agnico-Eagle Mines': 'Agnico Eagle Mines',
    'Air France-KLM': 'Air France-KLM Group',
    'Air Lease': 'Air Lease Corporation',
    'Air Prods & Chems': 'Air Products & Chemicals',
    'Aire Liquide Group': 'Air Liquide',
    # 'Aker Kvaerner': 'Aker Solutions',
    # 'Aker': 'Aker Solutions',
    'Alibaba': 'Alibaba Group',
    'Alibaba.com': 'Alibaba Group',
    'Alpha Bank Group': 'Alpha Bank',
    'Alps Electric Co': 'Alps Electric',
    'Amadeus IT Holdings': 'Amadeus IT Group',
    'Amazon': 'Amazon.com',
    'American Capital Agency': 'AGNC Investment',
    'American Capital Agency Corp.': 'AGNC Investment',
    'American Equity Invest': 'American Equity Investment',
    'American Finl Group': 'American Financial Group',
    'American Intl Group': 'American International Group',
    'American Natl Ins': 'American National Insurance',
    'Anheuser-Busch Cos': 'Anheuser-Busch',
    'Annaly Capital Mgmt': 'Annaly Capital Management',
    'Antarchile': 'AntarChile',
    'Archer Daniels': 'Archer Daniels Midland',
    'Areva Group': 'Areva',
    'Aroundtown Property Holdings': 'Aroundtown',
    'Assoc British Foods': 'Associated British Foods',
    'Atos Origin': 'Atos',
    'Automatic Data': 'Automatic Data Processing',
    'Avalonbay Communities': 'AvalonBay Communities',
    'Ayala': 'Ayala Corporation',
    'Ayala Corp': 'Ayala Corporation',
    'BBVA Banco Continental': 'Banco BBVA Peru',
    'BCV': 'BCV Group',
    'BHP Billiton': 'BHP Group',
    'BMCE-Banque Marocaine': 'BMCE Bank',
    'BMW-Bayerische Motor': 'BMW Group',
    'BPER-Emilia Romagna': 'BPER Banca',
    "Banca Popolare dell'Emilia": 'BPER Banca',
    'BCP-Banco Com Português': 'Banco Comercial Português',
    'BRF-Brasil Foods': 'BRF',
    'Baker Hughes Company': 'Baker Hughes',
    'Banca CARIGE': 'Banca Carige',
    'Banco BPM': 'Banco BPM SpA',
    'Banco BTG Pactual Participations': 'Banco Btg Pactual',
    'Banco Comercial Portugues': 'Banco Comercial Português',
    'Banco Popular Espanol': "Banco Popular Español",
    'BanColombia': 'Bancolombia',
    'British Amer Tobacco': 'British American Tobacco',
    'Bta Bank': 'BTA Bank',
    'Bureau Veritas Registre International de Classific': 'Bureau Veritas',
    'Bank Danamon Indonesia': 'Bank Danamon',
    'Bank Rakyat Indonesia (BRI)': 'Bank Rakyat Indonesia',
    'Banque Nat de Belgique': 'Banque Nationale de Belgique',
    'Banque Nationale Belgique': 'Banque Nationale de Belgique',
    'Banque nationale de Belgique': 'Banque Nationale de Belgique',
    'Bayer Group': 'Bayer',
    'Becton, Dickinson': 'Becton Dickinson',
    'Bendigo & Adelaide Bank': 'Bendigo Bank',
    'Bilfinger & Berger': 'Bilfinger',
    'Biogen Idec': 'Biogen',
    'Bouygues Group': 'Bouygues',
    'Brookfield Asset Mgmt': 'Brookfield Asset Management',
    'Brother Inds': 'Brother Industries',
    'Burlington Stores,': 'Burlington Stores',
    'C.H. Robinson Worldwide': 'C.H. Robinson',
    'CAM': 'CAM Group',
    'CBOE Holdings': 'CBOE Global Markets',
    'CEZ': 'CEZ Group',
    'CFS Retail Property Trust': 'CFS Retail Property',
    'CJ': 'CJ CheilJedang',
    'CJ Cheiljedang': 'CJ CheilJedang',
    'CJ Corp': 'CJ Corporation',
    'CPI Property Group.': 'CPI Property Group',
    'CSN': 'Companhia Siderúrgica Nacional',
    'CSN-Cia Siderurgica': 'Companhia Siderúrgica Nacional',
    'Companhia Siderurgica': 'Companhia Siderúrgica Nacional',
    'Cablevision Systems': 'Cablevision Systems Corporation',
    'Cadbury Schweppes': 'Cadbury',
    'Canadian National': 'Canadian National Railway',
    'Canadian Natural Res': 'Canadian Natural Resources',
    'Capita Group': 'Capita',
    'Carrefour Group': 'Carrefour',
    'Challenger Financial Svcs': 'Challenger Ltd',
    'Charter Commun': 'Charter Communications',
    'Cheung Kong': 'Cheung Kong Holdings',
    'Cheung Kong Property Holdings': 'Cheung Kong Holdings',
    'China State Construction': 'China State Construction Engineering',
    'China Development Finl': 'China Development Financial',
    'China Everbright International': 'China Everbright',
    'China International Marine': 'China International Marine Containers',
    'China Intl Marine Container': 'China International Marine Containers',
    'China Minsheng Banking': 'China Minsheng Bank',
    'China Resources Cement Holdings': 'China Resources Cement',
    'China Resources Ent': 'China Resources Enterprise',
    'China Resources Power Holdings': 'China Resources Power',
    'China Unicom (HK)': 'China Unicom',
    'Chinese Estates': 'Chinese Estates Holdings',
    'Chinese Estates (Holdings)': 'Chinese Estates Holdings',
    'Cognizant Technology': 'Cognizant',
    'Commerce Bancshs': 'Commerce Bancshares',
    'Commercial Bank Kuwait': 'Commercial Bank of Kuwait',
    'Commercial Bank Qatar': 'Commercial Bank of Qatar',
    'Community Health Sys': 'Community Health Systems',
    'ConAgra Foods': 'Conagra Brands',
    'Core-Mark Holding Company': 'Core-Mark Holding',
    'Crown Castle Intl': 'Crown Castle International',
    'CVS Caremark': 'CVS Health',
    'DBS Group':'DBS',
    'DR Horton': 'D.R. Horton',
    'DSV Group': 'DSV',
    'Delphi Automotive': 'Delphi',
    'DSV Panalpina': 'DSV',
    'Deutsche Post': 'Deutsche Post DHL',
    'Danske Bank Group': 'Danske Bank',
    'Dassault Systemes': 'Dassault Systèmes',
    'Datang Intl Power': 'Datang International Power',
    'Deere & Co': 'John Deere',
    'Deere & Company': 'John Deere',
    'Dell Technologies': 'Dell',
    'DirecTV Group': 'Directv',
    'Dufry AG': 'Dufry',
    'Dow Chemical': 'DowDuPont',
    'EDF Group': 'EDF',
    'Edp-energias De Portugal': 'EDP-Energias de Portugal',
    'Electric Power Dev': 'Electric Power Development',
    'Electric Power Devel': 'Electric Power Development',
    'Eli Lilly': 'Eli Lilly & Co',
    'Ensco': 'Ensco International',
    'Erste Group Bank': 'Erste Bank',
    'Espirito Santo Financiall': 'Espirito Santo Financial',
    'Espirito Santo Finl': 'Espirito Santo Financial',
    'Estee Lauder Cos': 'Estée Lauder Companies',
    'Estée Lauder': 'Estée Lauder Companies',
    'Estée Lauder Cos': 'The Estée Lauder Companies',
    'Expedia Group': 'Expedia',
    'Expeditors Intl': 'Expeditors International',
    'Experian Group': 'Experian',
    'Exxon Mobil': 'ExxonMobil',
    'EnCana': 'Encana',
    'Formosa Chemicals': 'Formosa Chemicals & Fibre Corporation',
    'Formosa Chems & Fibre': 'Formosa Chemicals & Fibre Corporation',
    'FIBI Holdings': 'FIBI Holding',
    'Federal Grid of UES': 'Federal Grid',
    'Fidelity National Finl': 'Fidelity National Financial',
    'Fidelity National Information': 'Fidelity National Info',
    'Fifth Third Bancorp': 'Fifth Third Bank',
    "Financiere de l'Odet": "Financière de l'Odet",
    'First American': 'First American Financial',
    'First Citizens Bank': 'First Citizens BancShares',
    'First Citizens Bcshs': 'First Citizens BancShares',
    'First Republic Bank CA': 'First Republic Bank',
    'First Solar,': 'First Solar',
    'Flextronics Intl': 'Flextronics International',
    'Forest Labs': 'Forest Laboratories',
    'Fortune Brands': 'Fortune Brands Home & Security',
    'Foshan Haitian Flavouring and Food': 'Foshan Haitian Flavouring and Food Company',
    'Freeport': 'Freeport-McMoRan',
    'Freeport Copper': 'Freeport-McMoRan',
    'Freeport-McMoRan Copper': 'Freeport-McMoRan',
    'Freeport-mcmoran': 'Freeport-McMoRan',
    'Frontier Commun': 'Frontier Communications',
    'Fuji Electric Holdings': 'Fuji Electric',
    'Fuji Heavy Inds': 'Fuji Heavy Industries',
    'GAIL (India)': 'GAIL India',
    'GCL-Poly Energy Hldgs': 'GCL-Poly Energy Holdings',
    'GDF Suez': 'GDF SUEZ',
    'GOME Electrical': 'GOME Electrical Appliances',
    'GOME Electrical Appliances Holding': 'GOME Electrical Appliances',
    'GS E&C': 'GS Engineering',
    'Galaxy Entertainment': 'Galaxy Entertainment Group',
    'Galp Energia SGPS': 'Galp Energia',
    'GameStop Corp.': 'GameStop',
    'Gas Natural Fenosa': 'Naturgy Energy Group',
    'Gas Natural Group': 'Naturgy Energy Group',
    'General Growth Prop': 'General Growth Properties',
    'Grupa LOTOS': 'Grupa Lotos',
    'Guangzhou Automobile': 'Guangzhou Automobile Group',
    'Guangzhou Automobile Group Co. Ltd.': 'Guangzhou Automobile Group',
    'Gulf Bank': 'Gulf Bank of Kuwait',
    'H&M - Hennes & Mauritz': 'H&M',
    'H&M Hennes & Mauritz': 'H&M',
    'Hakuhodo DY': 'Hakuhodo DY Holdings',
    'Hammerson plc': 'Hammerson',
    # 'Hanjin Shipping Co': 'Hanjin Shipping',
    # 'Hanjin Shipping Holdings': 'Hanjin Shipping',
    'Hankyu Hanshin': 'Hankyu Hanshin Holdings',
    'Hartford Finl Service': 'Hartford Financial Services',
    'Hartford Finl Svcs': 'Hartford Financial Services',
    'Helvetia Group': 'Helvetia',
    'Helvetia Holding': 'Helvetia',
    'Helvetia Patria': 'Helvetia',
    'Henan Shuanghui Invest': 'Henan Shuanghui Investment',
    'Hengan Intl Group': 'Hengan International Group',
    'Hengyi Petrochemical Co., Ltd.': 'Hengyi Petrochemical',
    'Henkel Group': 'Henkel',
    'Hero Motocorp': 'Hero MotoCorp',
    'Hewlett Packard Enterprise': 'Hewlett-Packard',
    'Hokuhoku Finl Group': 'Hokuhoku Financial Group',
    'Hon Hai Precision Ind': 'Hon Hai Precision',
    'Hong Leong Financial': 'Hong Leong Financial Group',
    'Hopson Development Holdings': 'Hopson Development',
    'Huadian Power Intl': 'Huadian Power International',
    'Huaneng Power Intl': 'Huaneng Power International',
    'Huishang Bank': 'Huishang Bank Corporation Limited',
    'Huntington Bancshs': 'Huntington Bancshares',
    'Huntington Bank': 'Huntington Bancshares',
    'Hyundai Eng & Const': 'Hyundai Engineering',
    'Hyundai Heavy Industries Holdings': 'Hyundai Heavy Industries',
    'Hyundai Marine & Fire Ins': 'Hyundai Marine & Fire',
    'Hilton Worldwide Holdings': 'Hilton',
    'Inbursa Financiero': 'Inbursa',
    'Industrial Alliance Insur': 'Industrial Alliance Insurance',
    'Indl Dev Bank of India': 'IDBI Bank',
    'Infosys Technologies': 'Infosys',
    'Ingersoll-Rand': 'Ingersoll Rand',
    'Inner Mongolia BaoTou': 'Inner Mongolia Baotou Steel',
    'Inner Mongolia Yitai': 'Inner Mongolia Yitai Coal',
    'Industries of Qatar': 'Industries Qatar',
    'Inpex Holdings': 'Inpex',
    'Intu Properties plc': 'Intu Properties',
    'Investor': 'Investor AB',
    'Innolux Display': 'Innolux',
    'Chimei Innolux': 'Innolux',
    'IKB': 'IKB Deutsche',
    'J. Front Retailing': 'J Front Retailing',
    'Jacobs Engineering': 'Jacobs',
    'Jefferies Financial': 'Jefferies Group',
    'Johnson Controls International': 'Johnson Controls',
    'Jones Lang LaSalle Inc.': 'Jones Lang LaSalle',
    'Jupiter Telecomunications': 'Jupiter Telecommunications',
    'JB Hunt Transport': 'J.B. Hunt Transport Services',
    'KWG Property Holding': 'KWG Group Holdings',
    'KT Corp': 'KT',
    'Kao Corp': 'Kao',
    'Kawasaki Heavy Inds': 'Kawasaki Heavy Industries',
    'Keppel Corp': 'Keppel',
    'Kingboard Chemical': 'Kingboard Holdings',
    'Kingboard Chemical Holdings': 'Kingboard Holdings',
    'Kloeckner & Co': 'Klöckner & Co',
    'Konica Minolta Business Solutions': 'Konica Minolta',
    'Koç Group': 'Koç Holding',
    'Kraft Foods Group': 'Kraft Foods',
    'Krung-Thai Bank': 'Krung Thai Bank',
    'Kuehne & Nagel International': 'Kuehne + Nagel',
    "L'Oréal Group": "L'Oréal",
    'Level 3 Commun': 'Level 3 Communications',
    'Lagardère SCA': 'Lagardère',
    'Lend Lease': 'Lendlease',
    'Lend Lease Group': 'Lendlease',
    'Lendlease Group': 'Lendlease',
    'Lloyds TSB Group': 'Lloyds Banking Group',
    "Lowe's": "Lowe's Companies",
    "Lowe's Cos": "Lowe's Companies",
    'LukOil': 'Lukoil',
    'Lukoil Holding': 'Lukoil',
    'Luzhou Lao Jiao': 'Luzhou Laojiao',
    'LyondellBasell Inds': 'LyondellBasell Industries',
    'Manulife Financial': 'Manulife',
    'Mashreqbank': 'Mashreq Bank',
    'MasterCard': 'Mastercard',
    'Maxim Integrated Prods': 'Maxim Integrated Products',
    'McCormick': 'McCormick & Company',
    'McCormick & Co': 'McCormick & Company',
    'McGraw-Hill Cos': 'McGraw-Hill',
    'Mediatek': 'MediaTek',
    'Melrose Industries Plc': 'Melrose Industries',
    'Midea Group Co. Ltd.': 'Midea Group',
    'Millicom Intl Cellular': 'Millicom International',
    'Mitsubishi Gas Chemical': 'Mitsubishi Gas Chemical Company',
    'Mitsubishi Gas Chemical Company,': 'Mitsubishi Gas Chemical Company',
    'Mitsubishi Heavy Inds': 'Mitsubishi Heavy Industries',
    'Mitsui Engineering & Ship': 'Mitsui Engineering & Shipbuilding',
    'Mitsui & Co': 'Mitsui',
    'Mitsui Sumitomo Ins': 'Mitsui Sumitomo Insurance Group',
    'Mondelez International': 'Mondelēz International',
    'Mxller-Maersk': 'Møller-Maersk',
    'Metro AG': 'Metro Group',
    'MOL': 'MOL Hungarian Oil',
    'NVR,': 'NVR',
    'Nan Ya Plastic': 'Nan Ya Plastics',
    'NASDAQ': 'Nasdaq',
    'NASDAQ OMX Group': 'Nasdaq',
    'Nasdaq OMX Group': 'Nasdaq',
    'NAB - National Australia Bank': 'National Australia Bank',
    'Natl Bank of Kuwait': 'National Bank of Kuwait',
    'Neste Oil': 'Neste',
    'Nestle': 'Nestlé',
    'Netease': 'NetEase',
    'Netease.com': 'NetEase',
    'New York Community': 'New York Community Bank',
    'New York Community Bancorp': 'New York Community Bank',
    'Nielsen': 'Nielsen Holdings',
    'NIKE': 'Nike',
    'Newell Rubbermaid': 'Newell Brands',
    'Navistar Intl': 'Navistar International',
    'Nippon Paper Group': 'Nippon Paper Industries',
    'Nippon Steel & Sumitomo Metal': 'Nippon Steel',
    'Nomura': 'Nomura Holdings',
    'Nürnberger': 'Nürnberger Beteiligungs',
    'OCI Co': 'OCI',
    'OHL Group': 'OHL',
    'Old Republic Intl': 'Old Republic International',
    'Ooredoo Q.P.S.C': 'Ooredoo',
    'Ooredoo Telecom': 'Ooredoo',
    'Orascom Construction Inds': 'Orascom Construction',
    'PGE Polska Grupa': 'PGE Polska Grupa Energetyczna',
    'PICC': 'PICC Property & Casualty',
    'PLDT': 'PLDT-Philippine LDT',
    'PPG': 'PPG Industries',
    'Palo Alto Networks,': 'Palo Alto Networks',
    'Penske Automotive': 'Penske Automotive Group',
    'Penske Automotive Gp': 'Penske Automotive Group',
    'Petrobras-Petróleo Brasil': 'Petrobras',
    'Pgnig Group': 'Pgnig-Polskie Górnictwo Naftowe',
    'Phosagro': 'PhosAgro',
    'Pioneer Natural Res': 'Pioneer Natural Resources',
    'Pirelli & C': 'Pirelli',
    'Plains Exploration': 'Plains Exploration & Production',
    'Poly Property Group Co.': 'Poly Property Group',
    'Poly Real Estate': 'Poly Real Estate Group',
    'Polyus Gold': 'Polyus',
    'Polyus Gold International': 'Polyus',
    'Porsche Automobil Holding': 'Porsche',
    'Postal Savings Bank Of China (PSBC)': 'Postal Savings Bank Of China',
    'Principal Financial Group': 'Principal Financial',
    'Prisa Group': 'Prisa',
    'ProSiebenSat1 Media': 'ProSiebenSat.1 Media',
    'Public Service Enterprise': 'Public Service Enterprise Group',
    'PTT Public Company': 'PTT PCL',
    'PTT': 'PTT PCL',
    'PGE': 'PGE Polska Grupa Energetyczna',
    'Pulte Homes': 'PulteGroup',
    'Qurate Retail': 'Qurate Retail Group',
    'RELX Group': 'RELX',
    'RHB Capital': 'RHB Bank',
    'Raiffeisen International Bank-Holding': 'Raiffeisen Bank International',
    'Raymond James Finl': 'Raymond James Financial',
    'Raytheon': 'Raytheon Technologies',
    'Red Eléctrica': 'Red Eléctrica de España',
    'Repsol-YPF': 'Repsol YPF',
    'Royal Ahold Delhaize N.V.': 'Royal Ahold',
    'S.f. Holding': 'S.F. Holding',
    'SCA': 'SCA-Svenska Cellulosa',
    'SMC': 'SMC Corporation',
    'SMC Corp': 'SMC Corporation',
    'SSAB Svenskt Stal': 'SSAB',
    'Sabanci Holding': 'Sabanci Group',
    'Sabesp-Saneamento Basico': 'Sabesp',
    'Samsung Electro-Mech': 'Samsung Electro-Mechanics',
    'Saudi Telecommunications': 'Saudi Telecom',
    'Scripps Networks': 'Scripps Networks Interactive',
    'SembCorp Industries': 'Sembcorp Industries',
    'Shandong Gold-Mining': 'Shandong Gold Mining',
    'Shanghai Fosun Pharmaceutical (group)': 'Shanghai Fosun Pharmaceutical',
    'Shanghai Industrial': 'Shanghai Industrial Holdings',
    'Shanghai Intl Airport': 'Shanghai International Airport',
    'Shanghai Pharma': 'Shanghai Pharmaceuticals',
    'Shanghai Pudong Dev Bk': 'Shanghai Pudong Development',
    "Shanxi Lu'an": "Shanxi Lu'an Environmental",
    'Shenzhen Develop Bank': 'Shenzhen Development Bank',
    'Shinhan Financial': 'Shinhan Financial Group',
    'Shionogi & Co': 'Shionogi',
    'Shionogi & Co.': 'Shionogi',
    'Sino-Ocean Land Hldgs': 'Sino-Ocean Land Holdings',
    'SinoPac Financial': 'SinoPac Financial Holdings',
    'Skyworks Solutions Inc.': 'Skyworks Solutions',
    'Société Générale Group': 'Société Générale',
    'Soho China Ltd.': 'Soho China',
    'Sompo': 'Sompo Japan Insurance',
    'Sonae SGPS': 'Sonae',
    'Songbird Estates plc': 'Songbird Estates',
    'Southern': 'Southern Company',
    'Southern Co': 'Southern Company',
    'St Galler Kantonalbank': 'St. Galler Kantonalbank',
    'State Bank of India Group': 'State Bank of India',
    'StatoilHydro': 'Statoil',
    'Steinhoff Intl Holdings': 'Steinhoff International',
    'Stockland Australia': 'Stockland',
    'Sumitomo Heavy Inds': 'Sumitomo Heavy Industries',
    'Sumitomo Metal Inds': 'Sumitomo Metal Industries',
    'Sumitomo Realty & Dev': 'Sumitomo Realty',
    'Swiss Re Group': 'Swiss Re',
    'Sinopec-China Petroleum': 'Sinopec',
    'SEB-Skand Enskilda Bank': 'SEB AB',
    'SEB': 'SEB AB',
    'TCL Corp': 'TCL',
    'TD Bank': 'TD Bank Group',
    'TD Bank Financial Group': 'TD Bank Group',
    'TDC': 'TDC Group',
    'TRW Automotive Hldgs': 'TRW Automotive Holdings',
    'Taishin Financial Holding': 'Taishin Financial Holdings',
    'Targa Resources Corp.': 'Targa Resources',
    'Tata Consultancy Svcs': 'Tata Consultancy Services',
    'Tate & Lyle Group': 'Tate & Lyle',
    'Teva Pharmaceutical Inds': 'Teva Pharmaceutical',
    'Tiffany & Co': 'Tiffany & Co.',
    'Tingyi': 'Tingyi Holding',
    'Travelers': 'Travelers Companies',
    'Travelers Cos': 'Travelers Companies',
    'Tesla Motors': 'Tesla',
    'Twenty-First Century Fox, Inc.': 'Twenty-First Century Fox',
    'UniCredit': 'UniCredit Group',
    'Unipol': 'Unipol Gruppo',
    'United Aircraft': 'United Aircraft Corporation',
    'United Continental Hldgs': 'United Continental Holdings',
    'Unum': 'Unum Group',
    'Valeant Pharma': 'Valeant Pharmaceuticals',
    'Vinci': 'Vinci Group',
    'Watson Pharma': 'Watson Pharmaceuticals',
    'Weatherford Intl': 'Weatherford International',
    'Wheelock': 'Wheelock & Co',
    'White Mountains Ins': 'White Mountains Insurance',
    'Williams': 'Williams Companies',
    'Williams Cos': 'Williams Companies',
    'Workday, Inc.': 'Workday',
    'XL Group': 'XL Capital',
    'Xishan Coal & Elec': 'Xishan Coal & Electricity',
    'Yahoo': 'Yahoo!',
    'Yamaguchi Financial': 'Yamaguchi Financial Group',
    'Yangzijiang Ship': 'Yangzijiang Shipbuilding',
    'Yuanta Financial Hldg': 'Yuanta Financial Holding',
    'Yuexiu Property Co.': 'Yuexiu Property',
}
