COMPANIES = {
    "ANZ": "ANZ Banking",
    "Adobe": "Adobe Systems ",
    "Activision": "Activision Blizzard",
    "Advanced Micro": "Advanced Micro Devices",
    "Air France-KLM": "Air France-KLM Group",
    "Air Lease": "Air Lease Corporation",
    "Air Prods & Chems": "Air Products & Chemicals",
    "Alibaba": "Alibaba Group",
    "Alibaba.com": "Alibaba Group",
    "Alpha Bank": "Alpha Bank Group",
    "Alps Electric Co": "Alps Electric",
    "Amazon.com": "Amazon",
    "American Capital Agency Corp": "American Capital Agency",
    "American Equity Invest": "American Equity Investment",
    "American Finl Group": "American Financial Group ",
    "American Intl Group": "American International Group",
    "American Natl Ins": "American National Insurance",
    "Angang New Steel": "Angang Steel",
    "Annaly Capital Mgmt": "Annaly Capital Management",
    "Archer Daniels": "Archer Daniels Midland",
    "Areva": "Areva Group",
    "Assoc British Foods": "Associated British Foods",
    "Automatic Data": "Automatic Data Processing",
    "Ayala": "Ayala Corporation",
    "BCV": "BCV Group",
    "Banque Nat de Belgique": "Banque Nationale de Belgique",
    "Banque Nationale Belgique": "Banque Nationale de Belgique",
    "Banque nationale de Belgique": "Banque Nationale de Belgique",
    "Bayer": "Bayer Group",
    "Bid Corp.": "Bid",
    "Bilfinger & Berger": "Bilfinger",
    "Biogen Idec": "Biogen",
    "Brookfield Asset Mgmt": "Brookfield Asset Management",
    "Brother Inds": "Brother Industries",
    "Bureau Veritas Registre International de Classific": "Bureau Veritas",
    "C.H. Robinson Worldwide": "C.H. Robinson",
    "CAM": "CAM Group",
    "CEZ": "CEZ Group",
    "CFS Retail Property Trust": "CFS Retail Property",
    "CJ Corp": "CJ Corporation ",
    "CJ": "CJ Corporation ",
    "CSN-Cia Siderurgica": "CSN",
    "CVS Caremark": "CVS Health",
    "Canadian Natural Res": "Canadian Natural Resources",
    "Capita": "Capita Group",
    "Carrefour": "Carrefour Group",
    "Charter Commun": "Charter Communications",
    "Cheung Kong": "Cheung Kong Property Holdings",
    "Cheung Kong Holdings": "Cheung Kong Property Holdings",
    "China Development Finl": "China Development Financial",
    "China Resources Cement": "China Resources Cement Holdings",
    "China Resources Ent": "China Resources Enterprise",
    "China Resources Power": " China Resources Power Holdings",
    "China State Construction": "China State Construction Engineering",
    "China Unicom (HK)": "China Unicom",
    "Chinese Estates (Holdings)": "Chinese Estates",
    "Cognizant Technology": "Cognizant",
    "Community Health Sys": "Community Health Systems",
    "Core-Mark Holding": "Core-Mark Holding Company",
    "DBS": "DBS Group",
    "DSV": "DSV Group",
    "Danske Bank": "Danske Bank Group",
    "Datang Intl Power": "Datang International Power",
    "Deere & Company": "Deere & Co",
    "Deutsche Post DHL": "Deutsche Post",
    "Directv": "Directv Group",
    "Dufry": "Dufry AG",
    "EDF": "EDF Group",
    "Electric Power Dev": "Electric Power Development",
    "Electric Power Devel": "Electric Power Development",
    "Eli Lilly": "Eli Lilly & Co",
    "Ensco": "Ensco International",
    "Erste Group Bank": "Erste Bank",
    "Espirito Santo Financiall": "Espirito Santo Financial",
    "Expedia": "Expedia Group",
    "ExxonMobil": "Exxon Mobil",
    "FIBI Holding": "FIBI Holdings ",
    "FMC": "FMC Technologies",
    "Federal Grid": "Federal Grid of UES",
    "Fidelity National Finl": "Fidelity National Financial",
    "Fidelity National Info": "Fidelity National Information",
    "Fifth Third Bank": "Fifth Third Bancorp",
    "First Citizens BancShares": "First Citizens Bank",
    "First Citizens Bcshs": "First Citizens Bank",
    "First Republic Bank CA": "First Republic Bank",
    "Flextronics Intl": "Flextronics International",
    "Formosa Chems & Fibre": "Formosa Chemicals",
    "Foshan Haitian Flavouring and Food": "Foshan Haitian Flavouring and Food Company",
    "Frontier Commun": "Frontier Communications",
    "Fuji Electric": "Fuji Electric Holdings",
    "Fuji Heavy Inds": "Fuji Heavy Industries",
    "GAIL (India)": "GAIL India",
    "GCL-Poly Energy Hldgs": "GCL-Poly Energy Holdings",
    "GOME Electrical": "GOME Electrical Appliances Holding",
    "Galaxy Entertainment": "Galaxy Entertainment Group",
    "Galp Energia": "Galp Energia SGPS",
    "GameStop Corp.": "GameStop",
    "Gas Natural Group": "Gas Natural Fenosa",
    "General Growth Prop": "General Growth Properties",
    "Guangzhou Automobile Group": "Guangzhou Automobile",
    "Guangzhou Automobile Group Co. Ltd.": "Guangzhou Automobile",
    "H&M - Hennes & Mauritz": "H&M",
    "H&M Hennes & Mauritz": "H&M",
    "Hakuhodo DY": "Hakuhodo DY Holdings",
    "Hanjin Shipping": "Hanjin Shipping Co",
    "Hankyu Hanshin": "Hankyu Hanshin Holdings",
    "Hartford Finl Service": "Hartford Financial Services",
    "Hartford Finl Svcs": "Hartford Financial Services",
    "Heineken Holding": "Heineken",
    "Helvetia": "Helvetia Group",
    "Helvetia Holding": "Hevetia Group",
    "Henan Shuanghui Invest": "Henan Shuanghui Investment",
    "Hengan Intl Group": "Hengan International Group",
    "Henkel": "Henkel Group",
    "Hewlett Packard Enterprise": "Hewlett-Packard",
    "Hilton Worldwide Holdings": "Hilton",
    "Hokuhoku Finl Group": "Hokuhoku Financial Group",
    "Hon Hai Precision Ind": "Hon Hai Precision",
    "Hong Leong Financial": "Hong Leong Financial Group",
    "Hopson Development": "Hopson Development Holdings",
    "Huadian Power Intl": "Huadian Power International",
    "Huaneng Power Intl": "Huaneng Power International",
    "Huishang Bank Corporation Limited": "Huishang Bank",
    "Huntington Bancshares": "Huntington Bank",
    "Huntington Bancshs": "Huntington Bank",
    "Hyundai Eng & Const": "Hyundai Engineering",
    "Hyundai Marine & Fire Ins": "Hyundai Marine & Fire",
    "Inbursa Financiero": "Inbursa",
    "Industrial Alliance Insur": "Industrial Alliance Insurance",
    "Industrial Bank China": "Industrial Bank",
    "Industries of Qatar": "Industries Qatar",
    "Infosys Technologies": "Infosys",
    "Ingersoll-Rand": "Ingersoll Rand",
    "Inner Mongolia BaoTou": "Inner Mongolia BaoTou Steel",
    "Inner Mongolia Yitai": "Inner Mongolia Yitai Coal",
    "Inpex Holdings": "Inpex",
    "Intu Properties plc": "Intu Properties",
    "Investor": "Investor AB",
    "JB Hunt Transport": "J.B. Hunt Transport Services",
    "Johnson Controls": "Johnson Controls International",
    "Jones Lang LaSalle Inc.": "Jones Lang LaSalle",
    "Julius Baer Holding": "Julius Baer Group",
    "Jupiter Telecomunications": "Jupiter Telecommunications",
    "KKPC-Korea Kumho": "KKPC",
    "KWG Property Holding": "KWG Group Holdings",
    "Kao Corp": "Kao",
    "Kawasaki Heavy Inds": "Kawasaki Heavy Industries",
    "Keppel Corp": "Keppel",
    "Konica Minolta": "Konica Minolta Business Solutions",
    "Kraft Foods Group": "Kraft Foods",
    "Krung-Thai Bank": "Krung Thai Bank",
    "Kuehne + Nagel": "Kuehne & Nagel International",
    "Lafarge": "LafargeHolcim",
    "Lend Lease": "Lendlease Group",
    "Lend Lease Group": "Lendlease Group",
    "Level 3 Commun": "Level 3 Communications",
    "Lowe's Cos": "Lowe's",
    "Luzhou Laojiao": "Luzhou Lao Jiao",
    "MOL": "MOL Hungarian Oil",
    "Manulife Financial": "Manulife",
    "Maxim Integrated Prods": "Maxim Integrated Products",
    "McGraw-Hill Cos": "McGraw-Hill",
    "Midea Group Co. Ltd.": "Midea Group",
    "Millicom Intl Cellular": "Millicom International",
    "Mitsubishi Heavy Inds": "Mitsubishi Heavy Industries",
    "Mitsui & Co": "Mitsui",
    "Mitsui Sumitomo Ins": "Mitsui Sumitomo Insurance Group",
    "Mxller-Maersk": "Møller-Maersk",
    "Nan Ya Plastic": "Nan Ya Plastics",
    "Navistar Intl": "Navistar International",
    "Neste Oil": "Neste",
    "New York Community": "New York Community Bancorp",
    "Nielsen Holdings": "Nielsen",
    "Nippon Paper Group": "Nippon Paper Industries",
    "Nishi-nippon Financial Holdings": "Nishi-Nippon City Bank",
    "Nomura Holdings": "Nomura",
    "Old Republic Intl": "Old Republic International",
    "Orascom Construction Inds": "Orascom Construction",
    "PGE Polska Grupa": "PGE",
    "PGE Polska Grupa Energetyczna": "PGE",
    "PLDT-Philippine LDT": "PLDT",
    "Penske Automotive Gp": "Penske Automotive",
    "People's Insurance Company": "People's Insurance",
    "Petrobras-Petróleo Brasil": "Petrobras",
    "Peugeot Groupe": "Peugeot",
    "Polyus Gold": "Polyus Gold International",
    "Porsche": "Porsche Automobil Holding",
    "Postal Savings Bank Of China (PSBC)": "Postal Savings Bank Of China",
    "Principal Financial": "Principal Financial Group",
    "Prisa Group": "Prisa ",
    "Public Service Enterprise": "Public Service Enterprise Group",
    "Qurate Retail": "Qurate Retail Group",
    "Raiffeisen International Bank-Holding": "Raiffeisen Bank International",
    "Raymond James Finl": "Raymond James Financial",
    "Red Eléctrica de España": "Red Eléctrica",
    "Repsol-YPF": "Repsol YPF",
    "Rolls-Royce": "Rolls-Royce Holdings",
    "Rolls-Royce Group": "Rolls-Royce Holdings",
    "Royal Ahold": "Royal Ahold Delhaize N.V.",
    "SSAB Svenskt Stal": "SSAB",
    "Samsung Electro-Mech": "Samsung Electro-Mechanics",
    "Saudi Telecommunications": "Saudi Telecom",
    "Scripps Networks": "Scripps Networks Interactive",
    "Shandong Gold-Mining": "Shandong Gold Mining",
    "Shanghai Fosun Pharmaceutical (group)": "Shanghai Fosun Pharmaceutical",
    "Shanxi Lu'an": "Shanxi Lu'an Environmental",
    "Shenzhen Develop Bank": "Shenzhen Development Bank",
    "Shionogi & Co.": "Shionogi",
    "Shionogi & Co": "Shionogi",
    "Sino-Ocean Group Holding": "Sino-Ocean Land Holdings",
    "Sino-Ocean Land Hldgs": "Sino-Ocean Land Holdings",
    "Standard Chartered Group": "Standard Chartered",
    "State Bank of India Group": "State Bank of India",
    "Stockland": "Stockland Australia",
    "Sumitomo Heavy Inds": "Sumitomo Heavy Industries",
    "Sumitomo Metal Inds": "Sumitomo Metal Industries",
    "Sumitomo Realty & Dev": "Sumitomo Realty",
    "Swiss Re Group": "Swiss Re",
    "TCL Corp": "TCL",
    "TD Bank Financial Group": "TD Bank Group",
    "TD Bank": "TD Bank Group",
    "TDC Group": "TDC",
    "Taishin Financial Holding": "Taishin Financial Holdings",
    "Taiwan Cooperative Bank": "Taiwan Cooperative Financial",
    "Tata Consultancy Svcs": "Tata Consultancy Services",
    "Thermo Fisher": "Thermo Fisher Scientific",
    "Tiffany & Co": "Tiffany & Co.",
    "Travelers Cos": "Travelers",
    "UNY": "UNY Group Holdings",
    "UniCredit Group": "UniCredit",
    "Unipol": "Unipol Gruppo",
    "United Continental Hldgs": "United Continental Holdings",
    "Unum Group": "Unum",
    "Valeant Pharma": "Valeant Pharmaceuticals",
    "Wheelock & Co": "Wheelock",
    "White Mountains Ins": "White Mountains Insurance",
    "Xishan Coal & Elec": "Xishan Coal & Electricity",
    "Yahoo": "Yahoo!",
    "Yamaguchi Financial Group": "Yamaguchi Financial",
    "Yangzijiang Ship": "Yangzijiang Shipbuilding",
    "Yuanta Financial Hldg": "Yuanta Financial Holding",
    "Yuexiu Property Co.": "Yuexiu Property",
    "Zain Group": "Zain"
}
